title: "Physical Computing 1"
email: casey.anderson@artcenter.edu
description:
    This prototyping-oriented class introduces students
    to the creative affordances of physical computing via
    hands-on experiments across a continuum of technologies.
baseurl: ""
url: "https://physcpu1.caseyanderson.com/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: caseyanderson

# Build settings
theme: minima
plugins:
  - jekyll-feed

# pages directory
include: [_pages]

# site defaults
defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /:categories/:title:output_ext
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
